from fpdf import FPDF
import datetime

class PDF(FPDF):
    def header(self):
        # Logo or Brand Name
        self.set_font('Arial', 'B', 20)
        self.set_text_color(44, 62, 80) # Dark Blue
        self.cell(0, 10, 'Dr. AI - Care Plan & Recommendations', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'DISCLAIMER: This is an AI-generated suggestion list for OTC (Over-the-Counter) relief. It is NOT a valid medical prescription.', 0, 0, 'C')

def create_prescription_pdf(symptoms, medicine_list, filename="Medication_Plan.pdf"):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- PATIENT INFO SECTION ---
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(0, 10, f"Reported Condition: {symptoms[:100]}...", ln=True)
    pdf.line(10, 45, 200, 45) # Horizontal line
    
    # --- MEDICINE LIST SECTION ---
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, "Suggested Medications (OTC) & Remedies:", ln=True)
    
    pdf.set_font("Arial", '', 11)
    pdf.set_text_color(0, 0, 0)
    
    # We expect medicine_list to be a long string from the AI. 
    # We clean it and print it neatly.
    clean_meds = medicine_list.replace("*", "").replace("#", "")
    pdf.multi_cell(0, 8, clean_meds)
    
    # --- DOCTOR SIGNATURE BLOCK ---
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, "Generated by Dr. AI Diagnostics System", ln=True, align='R')
    
    pdf.output(filename)
    return filename

# Keep the old function for backward compatibility if needed
def create_pdf_report(patient_data, doctor_analysis, filename="medical_report.pdf"):
    return create_prescription_pdf(patient_data, doctor_analysis, filename)